/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { RecognitionModelUpdateManyWithoutWorkspacesInput } from "./RecognitionModelUpdateManyWithoutWorkspacesInput";
import { Type } from "class-transformer";
import { CameraUpdateManyWithoutWorkspacesInput } from "./CameraUpdateManyWithoutWorkspacesInput";
import { UserUpdateManyWithoutWorkspacesInput } from "./UserUpdateManyWithoutWorkspacesInput";
import { RuleUpdateManyWithoutWorkspacesInput } from "./RuleUpdateManyWithoutWorkspacesInput";
import { ZoneUpdateManyWithoutWorkspacesInput } from "./ZoneUpdateManyWithoutWorkspacesInput";
import { NotificationUpdateManyWithoutWorkspacesInput } from "./NotificationUpdateManyWithoutWorkspacesInput";
import { StatisticUpdateManyWithoutWorkspacesInput } from "./StatisticUpdateManyWithoutWorkspacesInput";
import { ApiSettingUpdateManyWithoutWorkspacesInput } from "./ApiSettingUpdateManyWithoutWorkspacesInput";
import { SupportRequestUpdateManyWithoutWorkspacesInput } from "./SupportRequestUpdateManyWithoutWorkspacesInput";

@InputType()
class WorkspaceUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecognitionModelUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => RecognitionModelUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => RecognitionModelUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  recognitionModels?: RecognitionModelUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => CameraUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => CameraUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => CameraUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  cameras?: CameraUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => RuleUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => RuleUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => RuleUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  rules?: RuleUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => ZoneUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => ZoneUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => ZoneUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  zones?: ZoneUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => NotificationUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => NotificationUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => NotificationUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  notifications?: NotificationUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => StatisticUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => StatisticUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => StatisticUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  statistics?: StatisticUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => ApiSettingUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => ApiSettingUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => ApiSettingUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  apiSettings?: ApiSettingUpdateManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => SupportRequestUpdateManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestUpdateManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => SupportRequestUpdateManyWithoutWorkspacesInput, {
    nullable: true,
  })
  supportRequests?: SupportRequestUpdateManyWithoutWorkspacesInput;
}

export { WorkspaceUpdateInput as WorkspaceUpdateInput };
