/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { RecognitionModelCreateNestedManyWithoutWorkspacesInput } from "./RecognitionModelCreateNestedManyWithoutWorkspacesInput";
import { Type } from "class-transformer";
import { CameraCreateNestedManyWithoutWorkspacesInput } from "./CameraCreateNestedManyWithoutWorkspacesInput";
import { UserCreateNestedManyWithoutWorkspacesInput } from "./UserCreateNestedManyWithoutWorkspacesInput";
import { RuleCreateNestedManyWithoutWorkspacesInput } from "./RuleCreateNestedManyWithoutWorkspacesInput";
import { ZoneCreateNestedManyWithoutWorkspacesInput } from "./ZoneCreateNestedManyWithoutWorkspacesInput";
import { NotificationCreateNestedManyWithoutWorkspacesInput } from "./NotificationCreateNestedManyWithoutWorkspacesInput";
import { StatisticCreateNestedManyWithoutWorkspacesInput } from "./StatisticCreateNestedManyWithoutWorkspacesInput";
import { ApiSettingCreateNestedManyWithoutWorkspacesInput } from "./ApiSettingCreateNestedManyWithoutWorkspacesInput";
import { SupportRequestCreateNestedManyWithoutWorkspacesInput } from "./SupportRequestCreateNestedManyWithoutWorkspacesInput";

@InputType()
class WorkspaceCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecognitionModelCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => RecognitionModelCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => RecognitionModelCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  recognitionModels?: RecognitionModelCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => CameraCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => CameraCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => CameraCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  cameras?: CameraCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => RuleCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => RuleCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => RuleCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  rules?: RuleCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => ZoneCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => ZoneCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => ZoneCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  zones?: ZoneCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => StatisticCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => StatisticCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => StatisticCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  statistics?: StatisticCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => ApiSettingCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => ApiSettingCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => ApiSettingCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  apiSettings?: ApiSettingCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => SupportRequestCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => SupportRequestCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  supportRequests?: SupportRequestCreateNestedManyWithoutWorkspacesInput;
}

export { WorkspaceCreateInput as WorkspaceCreateInput };
