/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { RecognitionModel } from "../../recognitionModel/base/RecognitionModel";
import { Camera } from "../../camera/base/Camera";
import { User } from "../../user/base/User";
import { Rule } from "../../rule/base/Rule";
import { Zone } from "../../zone/base/Zone";
import { Notification } from "../../notification/base/Notification";
import { Statistic } from "../../statistic/base/Statistic";
import { ApiSetting } from "../../apiSetting/base/ApiSetting";
import { SupportRequest } from "../../supportRequest/base/SupportRequest";

@ObjectType()
class Workspace {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: () => [RecognitionModel],
  })
  @ValidateNested()
  @Type(() => RecognitionModel)
  @IsOptional()
  recognitionModels?: Array<RecognitionModel>;

  @ApiProperty({
    required: false,
    type: () => [Camera],
  })
  @ValidateNested()
  @Type(() => Camera)
  @IsOptional()
  cameras?: Array<Camera>;

  @ApiProperty({
    required: false,
    type: () => [User],
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  users?: Array<User>;

  @ApiProperty({
    required: false,
    type: () => [Rule],
  })
  @ValidateNested()
  @Type(() => Rule)
  @IsOptional()
  rules?: Array<Rule>;

  @ApiProperty({
    required: false,
    type: () => [Zone],
  })
  @ValidateNested()
  @Type(() => Zone)
  @IsOptional()
  zones?: Array<Zone>;

  @ApiProperty({
    required: false,
    type: () => [Notification],
  })
  @ValidateNested()
  @Type(() => Notification)
  @IsOptional()
  notifications?: Array<Notification>;

  @ApiProperty({
    required: false,
    type: () => [Statistic],
  })
  @ValidateNested()
  @Type(() => Statistic)
  @IsOptional()
  statistics?: Array<Statistic>;

  @ApiProperty({
    required: false,
    type: () => [ApiSetting],
  })
  @ValidateNested()
  @Type(() => ApiSetting)
  @IsOptional()
  apiSettings?: Array<ApiSetting>;

  @ApiProperty({
    required: false,
    type: () => [SupportRequest],
  })
  @ValidateNested()
  @Type(() => SupportRequest)
  @IsOptional()
  supportRequests?: Array<SupportRequest>;
}

export { Workspace as Workspace };
