/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WorkspaceWhereUniqueInput } from "../../workspace/base/WorkspaceWhereUniqueInput";
import { Type } from "class-transformer";
import { RuleUpdateManyWithoutCamerasInput } from "./RuleUpdateManyWithoutCamerasInput";
import { ZoneUpdateManyWithoutCamerasInput } from "./ZoneUpdateManyWithoutCamerasInput";
import { StatisticUpdateManyWithoutCamerasInput } from "./StatisticUpdateManyWithoutCamerasInput";

@InputType()
class CameraUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ipAddress?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  settings?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => WorkspaceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkspaceWhereUniqueInput)
  @IsOptional()
  @Field(() => WorkspaceWhereUniqueInput, {
    nullable: true,
  })
  workspace?: WorkspaceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => RuleUpdateManyWithoutCamerasInput,
  })
  @ValidateNested()
  @Type(() => RuleUpdateManyWithoutCamerasInput)
  @IsOptional()
  @Field(() => RuleUpdateManyWithoutCamerasInput, {
    nullable: true,
  })
  rules?: RuleUpdateManyWithoutCamerasInput;

  @ApiProperty({
    required: false,
    type: () => ZoneUpdateManyWithoutCamerasInput,
  })
  @ValidateNested()
  @Type(() => ZoneUpdateManyWithoutCamerasInput)
  @IsOptional()
  @Field(() => ZoneUpdateManyWithoutCamerasInput, {
    nullable: true,
  })
  zones?: ZoneUpdateManyWithoutCamerasInput;

  @ApiProperty({
    required: false,
    type: () => StatisticUpdateManyWithoutCamerasInput,
  })
  @ValidateNested()
  @Type(() => StatisticUpdateManyWithoutCamerasInput)
  @IsOptional()
  @Field(() => StatisticUpdateManyWithoutCamerasInput, {
    nullable: true,
  })
  statistics?: StatisticUpdateManyWithoutCamerasInput;
}

export { CameraUpdateInput as CameraUpdateInput };
